"""create distraction table

Revision ID: 298e8829acb6
Revises: 
Create Date: 2022-03-04 16:10:40.694934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298e8829acb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distraction')
    # ### end Alembic commands ###
